import { Geist, Geist_Mono } from "next/font/google";
import {Poppins} from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";
import AuthProvider from "@/components/AuthProvider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "ConnectHive | Connecting one at a time",
  description: "Generated by create next app",
};
 const poppins = Poppins({
 subsets:["latin"],
 weight:["100","200","300","400","500","600","700","800","900",]
 })

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${poppins.className} antialiased`}
      >
        <AuthProvider/>
        <Navbar/>
        {children}
        <Footer/>
       
      </body>
    </html>
  );
}
